# Generated by Django 5.1 on 2024-10-18 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.room",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="messages",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
